# Configuration file for running the test suite. Results will be at https://travis-ci.org/phpList/phplist3
# whitelist
dist: trusty
language: php
php:
  - 7.1
  - 7.0
  - 5.6
  - 5.5

before_script:
  - sudo apt-get update > /dev/null
  - composer self-update
  - composer install --prefer-dist

script:
  - vendor/njoannidi/php-lint-bash/phpLint 

after_failure:
  - echo "Failures detected."
